config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links
  get ':slug' => 'links#show'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  after_create :generate_slug
  validates :given_url, presence: true

  def generate_slug
    self.slug = self.id.to_s(36)
    self.save
  end

  def display_slug
    ENV['BASE_URL'] + self.slug
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @link = Link.new
    @top_links = Link.order(clicks: :desc).first(12)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]
  before_action :authenticate_user!, only: [:index, :create, :destroy, :show]

  def index
    @links = Link.all
  end

  def show
    if params[:slug]
      @link = Link.find_by(slug: params[:slug])
      if redirect_to @link.given_url
        @link.clicks += 1
        @link.save
      end
    else
      @link = Link.find(params[:id])
    end
  end

  def create
    @link = Link.new(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to root_path, notice: 'successfully created.' }
        format.js
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to root_path
  end

  private
  def set_link
    @link = Link.find_by(slug: params[:slug])
  end
  def link_params
    params.require(:link).permit(:given_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/home/index.html.erb
<div class="row">
  <%= render 'links/form' %>
</div>

<div class="alert">
  <% flash[:notice] %>
</div>

<div class="title">
  <h1>Trending links</h1>
</div>

<div class="container">
  <% @top_links.each do |link| %>
 <hr>
    <div class="row">
        <div class="col-sm-2">
          <ul class="click_time">
            <li><span class="badge"><span class="clicks"><%= link.clicks %></span></span> clicks</li>
            <li><span class="time"><%= time_ago_in_words(link.created_at) %> ago</span></li>
          </ul>
        </div>
        <div class="col-sm-3">
          <p class="short_url">Shortened URL:<%= link_to link.display_slug, link.slug, class: "btnSlug", target: "_blank" %></p>
        </div>
        <div class="col-sm-5">
          <p class="short_url">URL :<%= link_to link.given_url, link.given_url, target: "_blank" %></p>
        </div>
        <div class="col-sm-1">
            <%= link_to 'Delete', link_path(link), method: :delete, class: "btn btn-danger btn-lg" %>
        </div>      
    </div>
  <% end %>
</div>

<script>
  $('.btnSlug').click(function(event){
    event.preventDefault();
    var win = window.open(this, '_blank');
    win.focus();
    location.reload();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-default" role="navigation">
      <div id="logo" class="navbar-brand"><%= link_to "UrlShortner", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if user_signed_in? %>
		    <ul class="nav navbar-nav navbar-right">
			  <li><%= link_to 'Account', edit_user_registration_path %></li>
			  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
			</ul>
		  <% else %>
			<ul class="nav navbar-nav pull-right">
		      <li><%= link_to 'Sign up', new_user_registration_path %></li>
			  <li><%= link_to 'Sign in', new_user_session_path %></li>
			</ul>
		  <% end %>
        </nav>
      </div>
    </header>
	
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :given_url, :class => "form-control", :placeholder => "Paste a link to shorten" %>
  </div>
  <div class="actions">
    <%= f.submit 'Shorten Me', :class => "btn btn-primary" %>
  </div>
<% end %>